# Site settings
title: Niko Marjanovic
description: 'Resume & projects'
url: 'http://nikomarjanovic.github.io'
baseurl: ''
profilepic: '/images/Marn.jpg'
bkimage: '/images/bk1.jpeg'
google_analytics: UA-XXXXXX-X
font_awesome: '48794c2e4d.js'

author:
  name: Niko Marjanovic
  email: nikomarj@hotmail.com
  twitter_username:
  github_username: NikoMarjanovic
  kaggle_username: nikomj
  linkedin_username: niko-marjanovic-950182144


# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
